version: '3'

services:
  update-ip:
    build: .
    container_name: update-ip
    networks:
      - backend
    volumes:
      - "./html:/var/www/html"
    environment:
      # This needs to be on the same network
      API_KEY: "random_api_key"
      PDNS_API_KEY: ""
      PDNS_SERVER: "https://dns-api.robol.it"
    ports:
      - 1080:80

networks:
  backend:
